funboard/blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post_detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('post_update/<int:pk>/', views.PostUpdate.as_view(), name='post_update'),
    path('post_delete/<int:pk>/', views.PostDelete.as_view(), name='post_delete'),
    path('register', views.RegisterUser.as_view(), name='register'),
    path('login', views.LoginUser.as_view(), name='login'),
    path('profile', views.profile, name='profile'),
    path('logout', views.logout_user, name='logout'),
    # path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    # path('<int:post_id>/comment/', views.PostComment.as_view(), name='post_comment'),
    path('post_add', views.PostAdd.as_view(), name='post_add'),
    path('edit_page', views.edit_page, name='edit_page'),
    path('email-confirmation-sent/', views.EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', views.UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', views.EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', views.EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

funboard/funboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('blog.urls', namespace='blog')),
]

funboard/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse



class Post(models.Model):

    class PublishedManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status=Post.Status.PUBLISHED)

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'


    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', null=True)
    cat = models.ForeignKey('Category', on_delete=models.CASCADE, null=True)
    body = models.TextField()
    image = models.ImageField(null=True, blank=True)
    video = models.FileField(upload_to='video/', null=True, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager()
    published = PublishedManager()

        
    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish']),]


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created']),]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


CATEGORIES = (
    ('Tanks', 'Танки'),
    ('Hill', 'Хилы'),
    ('DD', 'ДД'),
    ('Merchants', 'Торговцы'),
    ('Guildmaster', 'Гилдмастеры'),
    ('Questgivers', 'Квестгиверы'),
    ('Blacksmith', 'Кузнецы'),
    ('Leatherman', 'Кожевники'),
    ('Potionist', 'Зельевары'),
    ('SpellMaster', 'Мастера заклинаний'),

)


class Category(models.Model):
    name = models.CharField(max_length=250, choices=CATEGORIES, blank=False, default=None)

    def __str__(self):
        return dict(CATEGORIES)[self.name]
    
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_img')

    def __str__(self):
        return f'{self.user.username} Profile'

funboard/blog/forms.py
from django import forms
from .models import Comment, Post
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body',]


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kargs):
        super().__init__(*args, **kargs)
        self.fields['cat'].empty_label = 'Категория не выбрана'
        

    class Meta:
        model = Post
        fields = ['title', 'body', 'cat', 'status', 'image', 'video']
        widgets = {
            'title': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Заголовок поста'
            }),

            'body': forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Текст поста'
            }),
            
            'image': forms.FileInput
        }


class RegisterUserForm(UserCreationForm):

    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': "inputPassword"}))
    password2 = forms.CharField(label='Re-enter password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': "inputPassword"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': "inputPassword"}))

funboard/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from .models import Post, Comment, UserProfile
from django.views.generic.edit import FormMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, TemplateView, View, DeleteView
from .forms import EmailPostForm, CommentForm, PostForm, RegisterUserForm, LoginUserForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.sites.models import Site
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required



class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


class PostDetail(FormMixin, DetailView):
    model = Post
    template_name = 'blog/post/detail.html'
    form_class = CommentForm
    

    def get_success_url(self, **kwargs):
        return reverse_lazy('blog:post_detail', kwargs={'pk':self.get_object().id})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.post = self.get_object()
        self.object.name = self.request.user
        self.object.save()
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        comments = post.comments.filter(active=True)
        context['post'] = post
        context['comments'] = comments
        return context


class PostAdd(LoginRequiredMixin, CreateView):
    template_name = 'blog/post/create.html'
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'blog/post/create.html'
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog/post/delete.html'
    success_url = reverse_lazy('blog:post_list')

        
def post_share(request, post_id):
    # Извлечь пост по его идентификатору id
    post = get_object_or_404(Post,
    id=post_id,
    status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        # Форма была передана на обработку
        form = EmailPostForm(request.POST)
        if form.is_valid():
        # Поля формы успешно прошли валидацию
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
            post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'your_account@gmail.com',
            [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
    'form': form,
    'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,
    id=post_id,
    status=Post.Status.PUBLISHED)
    comment = None
    # Комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Создать объект класса Comment, не сохраняя его в базе данных
        comment = form.save(commit=False)
        # Назначить пост комментарию
        comment.post = post
        # Сохранить комментарий в базе данных
        comment.save()
    return render(request, 'blog/post/comment.html',
    {'post': post,
    'form': form,
    'comment': comment})


def edit_page(request):

    template = 'blog/post/edit_page.html'
    context = {

    }

    return render(request, template, context)


class RegisterUser(CreateView):
    template_name = 'blog/users/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('blog:post_list')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # Функционал для отправки письма и генерации токена
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('blog:confirm_email', kwargs={'uidb64': uid, 'token': token})
        # current_site = Site.objects.get_current().domain
        send_mail(
            'Подтвердите свой электронный адрес',
            f'Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной почты: http://127.0.0.1:8000{activation_url}',
            'service.notehunter@gmail.com',
            [user.email],
            fail_silently=False,
        )
        return redirect('blog:email_confirmation_sent')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'blog/users/login.html'

    def get_success_url(self):
        return reverse_lazy('blog:post_list')
    

def logout_user(request):
    logout(request)
    return redirect('blog:login')

@login_required
def profile(request):
    user_posts = Post.objects.filter(author=request.user)
    post_ids = user_posts.values_list('id', flat=True)
    post_comment = Comment.objects.filter(post__id__in=post_ids)
    context = {
        'posts': user_posts,
        'comments': post_comment,
    }
    return render(request, 'blog/users/profile.html', context)

User = get_user_model()

class UserConfirmEmailView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('blog:email_confirmed')
        else:
            return redirect('blog:email_confirmation_failed')
        

class EmailConfirmationSentView(TemplateView):
    template_name = 'blog/users/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context

class EmailConfirmedView(TemplateView):
    template_name = 'blog/users/email_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context

class EmailConfirmationFailedView(TemplateView):
    template_name = 'blog/users/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context

funboard/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
 {% if comment %}
 <h2>Your comment has been added.</h2>
 <p><a href="{% url 'blog:post_detail' post.id %}">Back to the post</a></p>
 {% else %}
 {% include "blog/post/includes/comment_form.html" %}
{% endif %}
{% endblock %}

funboard/blog/templates/blog/post/create.html
{% extends 'blog/base.html' %}
{% block title %}Добавление поста{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <h1>Форма добавления</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.title }}
            {{ form.body }}
            {{ form.cat }}
            {{ form.status }}
            {{ form.image }}
            {{ form.video }}
            <button class="btn btn-success" type="submit">Добавить пост</button>
            <span>{{ error }}</span>
    {% else %}
        Пройдите регистрацию или войдите под своей учетной записью
    {% endif %}
  </form>
{% endblock %}

funboard/blog/templates/blog/post/delete.html
{% extends 'blog/base.html' %}
{% block title %}Удаление поста{% endblock %}
{% block content %}
  <h1>Удаление новости</h1>
  <form method="post">
    {% csrf_token %}
    <h2>{{ object.title }}</h2>
    <p>{{ object.body }}</p>
    <button class="btn btn-success" type="submit">Удалить пост</button>
    <span>{{ error }}</span>
  </form>
{% endblock %}

funboard/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date"> Опубликовано {{ post.publish }}  {{ post.author }} <strong>Ктегория {{ post.cat }}</strong></p>
    {{ post.body|linebreaks }}
        {% if post.image %}
            <img src="{{ post.image.url }}" alt="{{ post.title }}" width="800" height="600">
        {% endif %}

        {% if post.video %}
            <video width="800" height="600" controls>
            <source src="{{ post.video.url }}" type="video/mp4">
            Your browser does not support the video tag.
            </video>
        {% endif %}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Поделиться</a>
    </p>
    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
        <p>Нет комментариев к посту.</p>
        {% if user.is_authenticated and request.user.username == post.author.username %}
        <a href="{% url 'blog:post_delete' post.id %}" class="btn btn-danger">Удалить пост</a>
        <a href="{% url 'blog:post_update' post.id %}" class="btn btn-primary">Редактировать</a>
        {% endif %}    
    {% endfor %}
    <div>
        {% if user.is_authenticated %}
        {% include "blog/post/includes/comment_form.html" %}
        {% endif %}    
    </div>
    
    
    
{% endblock %}

funboard/blog/templates/blog/post/edit_page.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

{% endblock content %}

funboard/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>Объявления</h1>
        {% for post in posts %}
        <h2>
            <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
        </h2>
        <p class="date"> Опубликовано {{ post.publish }}  {{ post.author }} <strong>Ктегория {{ post.cat }}</strong></p>
        {{ post.body|truncatewords:30|linebreaks }}
        {% endfor %}
        {% if user.is_authenticated %}
        <a href="{% url 'blog:post_add' %}" class="btn btn-primary">Добавить пост</a>
        {% endif %}
        {% include 'blog/pagination.html' with page=page_obj %}

{% endblock %}

funboard/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
        "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
        {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}